//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Training.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a contact.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the last contact.
        /// </summary>
        public static string DelButton {
            get {
                return ResourceManager.GetString("DelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new contact.
        /// </summary>
        public static string EcranNameAddContact {
            get {
                return ResourceManager.GetString("EcranNameAddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Address.
        /// </summary>
        public static string EcranNameCarnetAdresse {
            get {
                return ResourceManager.GetString("EcranNameCarnetAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Address.
        /// </summary>
        public static string EcranNameGridAdresse {
            get {
                return ResourceManager.GetString("EcranNameGridAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title empty.
        /// </summary>
        public static string ErrMsgSelectedTitle {
            get {
                return ResourceManager.GetString("ErrMsgSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name does not empty !!!.
        /// </summary>
        public static string ErrName {
            get {
                return ResourceManager.GetString("ErrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string HeaderColumnGender {
            get {
                return ResourceManager.GetString("HeaderColumnGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string HeaderColumnName {
            get {
                return ResourceManager.GetString("HeaderColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string HeaderColumnSurname {
            get {
                return ResourceManager.GetString("HeaderColumnSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname :.
        /// </summary>
        public static string LabelSurName {
            get {
                return ResourceManager.GetString("LabelSurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title :.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        public static string TitleMlle {
            get {
                return ResourceManager.GetString("TitleMlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misses.
        /// </summary>
        public static string TitleMme {
            get {
                return ResourceManager.GetString("TitleMme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mister.
        /// </summary>
        public static string TitleMr {
            get {
                return ResourceManager.GetString("TitleMr", resourceCulture);
            }
        }
    }
}
